version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony-php
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    ports:
      - 9090:9000

  nginx:
    image: nginx:alpine
    container_name: symfony-nginx
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - .:/var/www/html
    ports:
      - 8080:80

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: symfony-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: